<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Bilder\Hintergund.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="SVG\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Bilder\Hintergund.png" />
  </ItemGroup>

</Project>
